# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo '************************************************************************************************POLARIS SAAS SCAN STARTED************************************************************************************************'
      curl -fLsS -o bridge.zip $(BRIDGE_URL)
      rm -rf /tmp/bridge && unzip -q -d /tmp/bridge bridge.zip && rm -f bridge.zip
      /tmp/bridge/bridge --stage polaris polaris.serverUrl=$(BRIDGE_POLARIS_SERVERURL) polaris.application.name=$(BRIDGE_POLARIS_APPLICATION_NAME) polaris.project.name=$(BRIDGE_POLARIS_PROJECT_NAME) polaris.assessment.types='["SAST","SCA"]' polaris.accessToken=$(BRIDGE_POLARIS_ACCESSTOKEN
      echo '************************************************************************************************POLARIS SAAS SCAN COMPLETE************************************************************************************************'