# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export BRIDGE_POLARIS_APPLICATION_NAME=rmichael-app
      export BRIDGE_POLARIS_PROJECT_NAME=P5
      curl -fLsS -o $(Agent.TempDirectory)/bridge.zip $BRIDGE
      unzip -qo -d $(Agent.TempDirectory)/bridge $(Agent.TempDirectory)/bridge.zip
      $(Agent.TempDirectory)/bridge/bridge --stage polaris polaris.assessment.types='["SAST","SCA"]'
  displayName: 'Polaris Scan'

